{
    "name": "Quanam Account Payable-Receivable by currency",
    "version": "18.0.1.7.0",
    "author": "Quanam",
    "website": "www.quanam.com",
    "category": "Account",
    'sequence': 45,
    'summary': "Upgrade de cliente y proveedor para configurar más de una cta contable a cobrar y pagar por moneda",
    "depends": ['account', 'l10n_latam_invoice_document'],
    "data": [
        "data/service_cron.xml",
        "security/ir.model.access.csv",
        "security/ir.model.access.csv",
        "security/partner_account_security.xml",
        "views/account_move_views.xml",
        "views/account_payment_method_line_views.xml",
        "views/account_payment_register_inherit_views.xml",
        "views/account_payment_view.xml",
        "views/partner_account_view.xml",
        "views/res_partner_views.xml",
        "views/tax_refund_legislation_config_views.xml",
        "views/res_config_settings_views.xml",
        "wizard/automatic_debit_payment_view.xml",
        "wizard/vat_refund_confirmationwizard_view.xml",
        "wizard/multi_invoice_payment_view.xml",
        "wizard/account_batch_payment_check_confirmation_view.xml",
    ],
    "installable": True,
    "license": "AGPL-3",
}
