# -*- coding: utf-8 -*-
{
    "name": "Quanam Cash Management",
    "version": "18.0.3.8.3",
    "author": "Quanam",
    "website": "www.quanam.com",
    "category": "Accounting/Accounting",
    "sequence": 45,
    "summary": "Localización Quanam para la Gestión de Caja Chica y Caja Central",
    "depends": ["base", "account", "account_q"],
    "data": [
        "data/ir_module_category_data.xml",
        "data/ir_sequence_data.xml",
        "security/cash_management_q_security.xml",
        "security/ir.model.access.csv",
        "wizard/opening_control_wizard.xml",
        "wizard/config_set_parent_wizard.xml",
        "views/account_move_views.xml",
        "views/cash_management_bill_views.xml",
        "views/cash_management_config_views.xml",
        "views/cash_management_session_views.xml",
        "views/dashboard_views.xml",
        "views/account_payment_register_inherit_views.xml",
        "views/payment_method_views.xml",
        "views/account_payment_views.xml",
        "views/cash_fund_transfer_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_items.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
