from . import res_partner_account
from . import res_partner
from . import account_payment
from . import account_move_line
from . import account_move
from . import account_payment_method_line
from . import tax_refund_legislation_config
from . import account_payment_register
from . import res_company
from . import res_config_settings
