# -*- coding: utf-8 -*-
{
    'name': 'Quanam l10n POS Configurations',
    "version": "18.0.1.2.1",
    'license': 'LGPL-3',
    'summary': 'Localización Quanam para las configuraciones del POS',
    'category': 'Purchase Management',
    'author': 'Quanam',
    'website': 'https://www.quanam.com',
    'depends': ['account_q'],
    'data': [
        'security/ir.model.access.csv',
        'data/account_payment_data.xml',
        'data/sequence_data.xml',
        'wizard/account_payment_register_inherit_views.xml',
        'wizard/multi_invoice_payment_view.xml',
        'views/account_journal_inherit_views.xml',
        'views/pos_transaction_log_views.xml',
        'views/pos_transaction_views.xml',
        'views/res_currency_views.xml',
        'views/pos_payment_provider_views.xml',
        'views/pos_payment_terminal_views.xml',
        'views/account_movel_inherit_views.xml',
        'views/menu_items.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
